// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awvrmbopxasgsyopxqka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3dnJtYm9weGFzZ3N5b3B4cWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NzE5NDgsImV4cCI6MjA3MTA0Nzk0OH0.6E26qu6H2KYUM2fKKnnmooWypPl04QxzqhScWuLP-W8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});